apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: functorhk
data:
  # Application Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PYTHONPATH: "/app:/app/enhanced_autogen_refactored"

  # Frontend configuration - Use absolute URLs for external access
  REACT_APP_API_URL: "http://45.77.206.161:30083/api"
  REACT_APP_WS_URL: "ws://45.77.206.161:30083/ws/reports"

  # CORS configuration override - temporarily allow all origins
  CORS_ORIGINS: "*"
  
  # System Configuration
  SYSTEM_NAME: "AgentInvest Financial Research Agents"
  SYSTEM_VERSION: "1.0.0"
  DEFAULT_RESEARCH_OBJECTIVE: "Comprehensive financial analysis and investment recommendation"
  DEFAULT_OUTPUT_FORMAT: "html"
  
  # Performance Configuration
  ENABLE_PERFORMANCE_TRACKING: "true"
  MAX_WORKFLOW_TIMEOUT_SECONDS: "300"
  MIN_QUALITY_SCORE: "0.80"
  MIN_CITATION_COUNT: "10"
  MIN_CONFIDENCE_SCORE: "0.75"
  
  # Embedding and Search Configuration
  EMBEDDING_MODEL: "all-MiniLM-L6-v2"
  IS_EMBEDDING: "true"
  KNN_MIN_SCORE: "0.94"
  DUPLICATE_TEXT_DISTANCE: "5"
  DUPLICATE_SCORE_VALUE: "0.97"
  EFFECTIVE_SEARCH_RATIO: "1"
  MAX_TOKEN_CHUNK_SIZE: "10000"
  NUMBER_OF_CHUNKS_TO_COMBINE: "6"
  UPDATE_GRAPH_CHUNKS_PROCESSED: "20"
  ENTITY_EMBEDDING: "False"
  GCS_FILE_CACHE: "False"
  
  # Model Configuration
  LLM_MODEL: "gpt-4.1-nano-2025-04-14"
  LLM_BASE_URL: "https://guoyixia.dpdns.org/v1"
  OPENAI_BASE_URL: "https://guoyixia.dpdns.org/v1"
  OPENAI_MODEL: "gpt-4.1-nano-2025-04-14"
  CRAWL4AI_OPENAI_BASE_URL: "https://guoyixia.dpdns.org/v1"
  CRAWL4AI_OPENAI_MODEL: "gpt-4.1-nano-2025-04-14"
  
  # LangChain Configuration
  LANGCHAIN_TRACING_V2: "true"
  LANGCHAIN_PROJECT: "agentinvest"
  LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
  
  # Gemini Configuration
  GEMINI_MODEL: "gemini-2.0-flash"
  GEMINI_URL: "https://www.chataiapi.com/v1"
  
  # Phoenix Configuration
  PHOENIX_COLLECTOR_ENDPOINT: "https://app.phoenix.arize.com/s/functor-hk"
  PHOENIX_PROJECT_NAME: "agentinvest"
  
  # Langfuse Configuration
  LANGFUSE_URL: "https://us.cloud.langfuse.com"
  
  # Weaviate Configuration
  WEAVIATE_URL: "bvs3stdqqcgdla3fs5xfw.c0.asia-southeast1.gcp.weaviate.cloud"
  WEAVIATE_SIMILARITY_THRESHOLD: "0.85"
  WEAVIATE_CACHE_FRESHNESS_HOURS: "24"
  
  # Neo4j Configuration
  NEO4J_URI: "neo4j+s://99b4c626.databases.neo4j.io"
  NEO4J_USERNAME: "neo4j"
  NEO4J_DATABASE: "neo4j"
  
  # Database Configuration - Disabled (PostgreSQL removed)
  USE_DATABASE: "false"

  # Redis Configuration - Local Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "agentinvest_redis_pass"
  REDIS_DB: "0"

  # Cache and Message Broker Configuration
  USE_CACHE: "true"
  USE_MESSAGE_BROKER: "false"

  # Model Configuration Strings
  # LLM_MODEL_CONFIG_gpt-4.1-nano-2025-04-14: "gpt-4.1-nano-2025-04-14,https://guoyixia.dpdns.org/v1"  # Moved to secrets
  LLM_MODEL_CONFIG_gemini_2.0_flash: "gemini-2.0-flash,https://www.chataiapi.com/v1"
