apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-pvc
  namespace: functorhk
  labels:
    app: webapp-backend
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vultr-block-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: functorhk
  labels:
    app: webapp-backend
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vultr-block-storage
  resources:
    requests:
      storage: 5Gi
