apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
  namespace: functorhk
type: Opaque
data:
  # API Keys (base64 encoded)
  OPENAI_API_KEY: c2stTmppaW5lbllHaXpuQ0RnWkYwbk9VSGlvZXBiVGY1UE15UjZPc3BGd1dpTmg3ajg1
  BRAVE_API_KEY: QlNBeGZSSm85aU9JY2NfZEZ4VjVrNWw0VEptdy1icA==
  BRAVE_SEARCH_API_KEY: QlNBeGZSSm85aU9JY2NfZEZ4VjVrNWw0VEptdy1icA==
  SEC_API_KEY: NmM5YzY3ZWQ1YzAxZGNiZDcyOWM1ZjM3MDk4ZmQyZThjYjQ5NzQxMDI0NWEzNDMyZTVlNWU0ZDJmYzhiOWUzYw==
  LANGCHAIN_API_KEY: bHN2Ml9wdF8zNDYxZWE2ZjIyNjU0YzJmOTU2N2JhNWRiYmZmZTc0ZV9hYWRkNTY1MjEx
  GEMINI_API_KEY: c2std0JNVW1xS3JwRThJc1NROWp4cGRPMkdEbmZIaVdiY3pzVlVoWGExNGhhbDdxUVpt
  PHOENIX_API_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnFkR2tpT2lKQmNHbExaWGs2TVNJOUxuTmhWRlYzTjB4d2RFWnBkRWxNYmpGMVNFMHlkMHBqWTJoSE9YcHpNbVZCY1V4VVVHOXpTVmR5TkE9PQ==
  LANGFUSE_SECRET_KEY: c2stbGYtYmQyODlmMDAtYmQ4Ny00MjEyLWJhN2ItNjFlZmU3OWM0NmZl
  LANGFUSE_PUBLIC_KEY: cGstbGYtZWUzN2VlNjYtMzE3NS00MjUxLWIzYjUtZmY3OWE0MzQxNzhj
  WEAVIATE_API_KEY: WTA5aFkwdzVhRnBSWWpWTEt6aDZUbDlKZVV4S1Z6bDJia0ZYYkZsVGNUbERPSGxzUjNKWU1VRjBPR3AyU1RGS01uTk1lVzU2WTFoVVFWbFJQVjkyTWpBdw==
  NEO4J_PASSWORD: eUxFT0xHYmFpRW5admkwZDJ1TFdELWxVRWdvNnF3U1RmYzZId0FIamhlSQ==
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfbzdmbEk4V3FuUVRpQGVwLXdpc3B5LXNreS1hZWJxMDB3cS1wb29sZXIuYy0yLnVzLWVhc3QtMi5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmU=
  POSTGRES_PASSWORD: bnBnX283ZmxJOFdxblFUaQ==
  LLM_MODEL_CONFIG_gpt_4o_mini: Z3B0LTRvLW1pbmksaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSxzay1OamlpaW5iWUdpem5DRGdaRjBuT1VIaW9lcGJUZjVQTXlSNk9zcEZ3V2lOaDdqODU=
  LLM_MODEL_CONFIG_gpt-4.1-nano-2025-04-14: Z3B0LTQuMS1uYW5vLTIwMjUtMDQtMTQsaHR0cHM6Ly9ndW95aXhpYS5kcGRucy5vcmcvdjEsc2stTmppaW5iWUdpem5DRGdaRjBuT1VIaW9lcGJUZjVQTXlSNk9zcEZ3V2lOaDdqODU=
  REDIS_PASSWORD: YWdlbnRpbnZlc3RfcmVkaXNfcGFzcw==
  POSTGRES_PASSWORD_LOCAL: QWdlbnRJbnZlc3QyMDI1IVNlY3VyZVBhc3M=
